http:
  routers:
    traefik:
      rule: "Host(`proxy.apollo.localhost`)"
      service: "api@internal"
      tls:
        domains:
          - main: "apollo.localhost"
            sans:
              - "*.apollo.localhost"
          - main: "apollo.local"
            sans:
              - "*.apollo.local"

tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"