http:
  routers:
    proxy:
      rule: "Host(`proxy.${HOST}`)"
      service: "api@internal"
      tls:
        domains:
          - main: "${HOST}"
            sans:
              - "*.${HOST}"
          - main: "${INTERNAL_HOST}"
            sans:
              - "*.${INTERNAL_HOST}"

tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"